# Generated by Django 5.2.5 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0022_surveyattempt_supplier_api_key_id_and_more"),
        ("vendors", "0019_vendorapikey_callback_secret_last_four_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TolunaNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("member_complete", "Member completion"), ("member_terminate", "Member termination"), ("enhanced_termination", "Enhanced termination"), ("quota_status", "Quota status"), ("survey_closed", "Survey closed"), ("reconciliation", "Reconciliation")], db_index=True, max_length=32)),
                ("payload_hash", models.CharField(max_length=64)),
                ("unique_code", models.CharField(blank=True, db_index=True, max_length=160)),
                ("provider_survey_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("survey_ref", models.CharField(blank=True, max_length=300)),
                ("wave_id", models.BigIntegerField(blank=True, null=True)),
                ("quota_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("provider_status", models.CharField(blank=True, db_index=True, max_length=80)),
                ("reason", models.CharField(blank=True, db_index=True, max_length=160)),
                ("rejection_id", models.BigIntegerField(blank=True, null=True)),
                ("rejection_name", models.CharField(blank=True, db_index=True, max_length=200)),
                ("reconciliation_id", models.BigIntegerField(blank=True, null=True)),
                ("revenue_cents", models.IntegerField(blank=True, null=True)),
                ("is_live", models.BooleanField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict, editable=False)),
                ("applied", models.BooleanField(db_index=True, default=False)),
                ("processing_message", models.CharField(blank=True, max_length=300)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_received_at", models.DateTimeField(auto_now=True)),
                ("attempt", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="toluna_notifications", to="surveys.surveyattempt")),
                ("integration", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="toluna_notifications", to="vendors.clientintegration")),
                ("survey", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="toluna_notifications", to="surveys.survey")),
            ],
            options={
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(fields=["event_type", "-received_at"], name="surveys_tol_event_t_e18031_idx"),
                    models.Index(fields=["integration", "event_type", "-received_at"], name="surveys_tol_integra_8380ac_idx"),
                    models.Index(fields=["attempt", "-received_at"], name="surveys_tol_attempt_c7f632_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("event_type", "payload_hash"), name="unique_toluna_notification_payload")],
            },
        ),
    ]
